### ISSUE TITLE
Template enhancement: SecretManagement Extension

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/PSModuleDevelopment#178]
Hi Fred,
I'm currently building an extension for the SecretManagement module. Many pitfalls...

I've used your templates for a base build of the modules and would like to develop a PSMD template for such extensions. Would it be ok for you if I contribute this template back to PSMD or does it have to be stored/provided elsewhere?

-Sascha aka callidus2000

**Comment by FriedrichWeinmann** [comment]
Heya Sascha,

thanks for offering and I am very open to new templates, so long as it is something I can reasonable review and maintain (complexity is not an issue, but .... let's just say I'd have concerns if it's ten thousand lines of code ;) ).
One thing to note:
The next major version of PSModuleDevelopment - there _is_ a new one in the works, but definitely not imminent - is going to have a few interesting commands, such as `Publish-PSMDTemplate`, `Find-PSMDTemplate` or `Install-PSMDTemplate`

**Comment by Callidus2000** [comment]
Hi,
then I'll create the template as a standalone module/repository for easier initial development. If the outcome meets your requirements I'd convert it into a PR of PSMD. 

Could you give some hints how the new functions will work?

**Comment by FriedrichWeinmann** [comment]
It's basically going to be like managing modules:
It will not change anything in how you build a template. The publish command is going to wrap up the template into a pseudo module and publish it to any repository you care to specify (so it works with internal repositories as well).
The Install command will deploy them to a new "templates" folder right beside the respective modules folder, which will be added as default template stores. On Windows that would be:

```text
%userprofile%\Documents\PowerShell\Templates
%programfiles%\PowerShell\Templates
```

or for Windows PowerShell:

```text
%userprofile%\Documents\WindowsPowerShell\Templates
%programfiles%\WindowsPowerShell\Templates
```

Also looking to respect a `$env:PSTemplatePath` environment variable, if it exists.

Again, this is purely a new way to _deploy_ templates, it will in no way affect how they are being invoked, once on the machine or in how they are being built and recorded in the first place. Though the new template-files, once built will become a lot smaller (I will include compression, without otherwise changing the format - templates built with older versions will still work just as fine with the upcoming version).

The `Publish-PSMDTemplate` command can target either the path to the template raws, the path to the built template file, or the name (and optionally store or version number) of the template. When targeting raws it will first call `New-PSMDTemplate` for you, but is otherwise identical to the other two options.

**Comment by Callidus2000** [comment]
Hi Fred,
I‘ve finished my template as a [separate modul](https://github.com/Callidus2000/SecretManagement.ExtensionTemplate). This way it was possible to use the project README as a documentation of best practices.

Thanks a lot for PSMD and PSF.

-Sascha
